version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: db_rooms
      MYSQL_ROOT_PASSWORD: 61hovumo
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=61hovumo--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    book-manager-app:
      restart: on-failure
      build: ./
      expose:
        - "8080"
      ports:
        - 10222:8080
      environment:
        WAIT_HOSTS: mysql:3306
      depends_on:
        - docker-mysql